/**
 * Governance Showcase Scenario — pedagogically designed project state
 * that exercises every governance skill with verifiable insights.
 *
 * Embedded violations:
 * 1. Epic Integrity: Auth epic E3 split across wave-002 and wave-003
 * 2. False Status: T10 "In Review" but no PR exists
 * 3. Cascade Blocker: T7→T8→T9 three-level dependency cascade
 * 4. Review Bottleneck: T12 stale in review
 * 5. Wave at Risk: wave-002 ~50% done with blocked/stale tasks
 */

import type { SandboxScenario } from '../types.js';

export const GOVERNANCE_SHOWCASE: SandboxScenario = {
  id: 'governance-showcase',
  name: 'Governance Showcase',
  description: 'A project with embedded governance violations for skill validation and onboarding',

  // ─── Waves ───
  waves: [
    {
      name: 'wave-001-foundation',
      description: 'Foundation wave — infrastructure setup',
      state: 'completed',
    },
    {
      name: 'wave-002-core',
      description: 'Core implementation — data pipeline and auth',
      state: 'active',
    },
    {
      name: 'wave-003-advanced',
      description: 'Advanced features — RBAC and dashboard',
      state: 'planned',
    },
    {
      name: 'wave-004-polish',
      description: 'Polish — documentation and guides',
      state: 'planned',
    },
  ],

  // ─── Epics ───
  epics: [
    {
      ref: 'E1',
      title: '[Epic] Setup & Infrastructure',
      body: [
        '## Setup & Infrastructure',
        '',
        'Foundation work: CI/CD, database, monitoring, dev environment, API contracts.',
        '',
        'All tasks in wave-001-foundation.',
      ].join('\n'),
    },
    {
      ref: 'E2',
      title: '[Epic] Data Pipeline',
      body: [
        '## Data Pipeline',
        '',
        'Data ingestion, ETL transformations, validation, rate limiting, export, and batch processing.',
        '',
        'All tasks in wave-002-core.',
      ].join('\n'),
    },
    {
      ref: 'E3',
      title: '[Epic] Authentication',
      body: [
        '## Authentication',
        '',
        'Auth tokens, OAuth, session management, and RBAC.',
        '',
        '**GOVERNANCE NOTE**: This epic intentionally has tasks split across',
        'wave-002-core and wave-003-advanced to demonstrate Epic Integrity violation detection.',
      ].join('\n'),
    },
    {
      ref: 'E4',
      title: '[Epic] Dashboard',
      body: [
        '## Dashboard',
        '',
        'Dashboard layout engine and widget framework.',
        '',
        'All tasks in wave-003-advanced.',
      ].join('\n'),
    },
    {
      ref: 'E5',
      title: '[Epic] Documentation',
      body: [
        '## Documentation',
        '',
        'User guide and API reference documentation.',
        '',
        'All tasks in wave-004-polish.',
      ].join('\n'),
    },
  ],

  // ─── Tasks ───
  tasks: [
    // ─── Wave 1 — Foundation (ALL DONE) ───
    {
      ref: 'T1',
      title: 'Set up CI/CD pipeline',
      body: [
        '## Set up CI/CD Pipeline',
        '',
        'Configure GitHub Actions for continuous integration and deployment.',
        '',
        '### Acceptance Criteria',
        '- [ ] Build pipeline runs on push to main',
        '- [ ] Test suite runs on all PRs',
        '- [ ] Deploy to staging on merge',
      ].join('\n'),
      epicRef: 'E1',
      wave: 'wave-001-foundation',
      status: 'DONE',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },
    {
      ref: 'T2',
      title: 'Initialize database schema',
      body: [
        '## Initialize Database Schema',
        '',
        'Design and implement the initial database schema with migrations.',
        '',
        '### Acceptance Criteria',
        '- [ ] Schema supports user, session, and data tables',
        '- [ ] Migration scripts run idempotently',
        '- [ ] Seed data available for development',
      ].join('\n'),
      epicRef: 'E1',
      wave: 'wave-001-foundation',
      status: 'DONE',
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T3',
      title: 'Configure monitoring',
      body: [
        '## Configure Monitoring',
        '',
        'Set up application monitoring and alerting.',
        '',
        '### Acceptance Criteria',
        '- [ ] Health check endpoint responds',
        '- [ ] Error rates tracked',
        '- [ ] Alert thresholds configured',
      ].join('\n'),
      epicRef: 'E1',
      wave: 'wave-001-foundation',
      status: 'DONE',
      effort: 'S',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },
    {
      ref: 'T4',
      title: 'Set up dev environment',
      body: [
        '## Set Up Dev Environment',
        '',
        'Docker compose and local development tooling.',
        '',
        '### Acceptance Criteria',
        '- [ ] `docker compose up` starts all services',
        '- [ ] Hot reload works for development',
        '- [ ] README documents setup steps',
      ].join('\n'),
      epicRef: 'E1',
      wave: 'wave-001-foundation',
      status: 'DONE',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T5',
      title: 'Define API contracts',
      body: [
        '## Define API Contracts',
        '',
        'OpenAPI specification for all REST endpoints.',
        '',
        '### Acceptance Criteria',
        '- [ ] OpenAPI 3.0 spec covers all endpoints',
        '- [ ] Request/response schemas defined',
        '- [ ] Generated types match implementation',
      ].join('\n'),
      epicRef: 'E1',
      wave: 'wave-001-foundation',
      status: 'DONE',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'HYBRID',
    },

    // ─── Wave 2 — Core (ACTIVE, mixed states) ───
    {
      ref: 'T6',
      title: 'Implement data ingestion',
      body: [
        '## Implement Data Ingestion',
        '',
        'Build the data ingestion pipeline for incoming data streams.',
        '',
        '### Acceptance Criteria',
        '- [ ] Supports CSV, JSON, and API sources',
        '- [ ] Validates input format before processing',
        '- [ ] Logs ingestion metrics',
      ].join('\n'),
      epicRef: 'E2',
      wave: 'wave-002-core',
      status: 'DONE',
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T7',
      title: 'Build ETL transformations',
      body: [
        '## Build ETL Transformations',
        '',
        'Core ETL pipeline for data transformations. **Long-running task that blocks downstream.**',
        '',
        '### Acceptance Criteria',
        '- [ ] Transform raw data to normalized schema',
        '- [ ] Handle schema evolution gracefully',
        '- [ ] Performance: 10k records/second throughput',
        '',
        '### Governance Signal',
        'This task is the root of a cascade blocker: T7 → T8 → T9.',
        'Unblocking T7 is the highest-leverage action for wave-002.',
      ].join('\n'),
      epicRef: 'E2',
      wave: 'wave-002-core',
      status: 'IN_PROGRESS',
      effort: 'XL',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
      contextComments: [
        'Started ETL transformations 4 days ago. Complex schema mapping proving harder than estimated. The source data has 12 different formats and edge cases keep appearing.',
      ],
    },
    {
      ref: 'T8',
      title: 'Data validation layer',
      body: [
        '## Data Validation Layer',
        '',
        'Validation rules engine for processed data. Blocked by ETL transformations.',
        '',
        '### Acceptance Criteria',
        '- [ ] Schema validation on all outputs',
        '- [ ] Custom validation rules configurable',
        '- [ ] Invalid records quarantined with reason',
        '',
        '### Governance Signal',
        'CASCADE DEPTH 1 — blocked by T7, blocks T9.',
      ].join('\n'),
      epicRef: 'E2',
      wave: 'wave-002-core',
      status: 'BLOCKED',
      effort: 'M',
      riskLevel: 'HIGH',
      aiSuitability: 'AI_REVIEWED',
      dependencyRefs: ['T7'],
      governanceSignal: 'CASCADE_BLOCKER_DEPTH_1',
      contextComments: [
        'Blocked by #T7 — waiting for ETL completion for 3 days. Validation rule design is ready, just need the data format to be finalized.',
      ],
    },
    {
      ref: 'T9',
      title: 'API rate limiting',
      body: [
        '## API Rate Limiting',
        '',
        'Rate limiter for API endpoints. Blocked by validation layer.',
        '',
        '### Acceptance Criteria',
        '- [ ] Token bucket algorithm implementation',
        '- [ ] Per-client rate limits configurable',
        '- [ ] Rate limit headers in responses',
        '',
        '### Governance Signal',
        'CASCADE DEPTH 2 — blocked by T8, which is blocked by T7.',
      ].join('\n'),
      epicRef: 'E2',
      wave: 'wave-002-core',
      status: 'BLOCKED',
      effort: 'S',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_ONLY',
      dependencyRefs: ['T8'],
      governanceSignal: 'CASCADE_BLOCKER_DEPTH_2',
      contextComments: [
        'Blocked by #T8 — cascade from ETL pipeline for 3 days. Rate limiter design complete, implementation waiting on validated data formats.',
      ],
    },
    {
      ref: 'T10',
      title: 'Auth token service',
      body: [
        '## Auth Token Service',
        '',
        'JWT token generation, validation, and refresh. **Marked as "In Review" but no PR exists.**',
        '',
        '### Acceptance Criteria',
        '- [ ] JWT generation with configurable expiry',
        '- [ ] Token refresh flow',
        '- [ ] Token revocation support',
        '',
        '### Governance Signal',
        'FALSE STATUS — this task is marked "In Review" but has no associated pull request.',
        '/standup should detect and flag this discrepancy.',
      ].join('\n'),
      epicRef: 'E3',
      wave: 'wave-002-core',
      status: 'IN_REVIEW',
      effort: 'L',
      riskLevel: 'CRITICAL',
      aiSuitability: 'HUMAN_ONLY',
      governanceSignal: 'FALSE_STATUS',
      contextComments: [
        'Moved to In Review 5 days ago. Note: implementation is still being finalized — no PR has been created yet. Waiting on security review of token rotation approach.',
      ],
    },
    {
      ref: 'T11',
      title: 'OAuth integration',
      body: [
        '## OAuth Integration',
        '',
        'OAuth 2.0 provider integration (Google, GitHub). Depends on auth token service.',
        '',
        '### Acceptance Criteria',
        '- [ ] OAuth 2.0 authorization code flow',
        '- [ ] Google and GitHub providers',
        '- [ ] Token exchange and storage',
      ].join('\n'),
      epicRef: 'E3',
      wave: 'wave-002-core',
      status: 'READY_FOR_DEV',
      effort: 'M',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
      dependencyRefs: ['T10'],
    },
    {
      ref: 'T12',
      title: 'Session management',
      body: [
        '## Session Management',
        '',
        'Server-side session handling with Redis backend. **Stale review — in review too long.**',
        '',
        '### Acceptance Criteria',
        '- [ ] Session creation and validation',
        '- [ ] Redis-backed session store',
        '- [ ] Session expiry and cleanup',
        '',
        '### Governance Signal',
        'REVIEW BOTTLENECK — this task has been "In Review" for an extended period.',
        '/standup should flag review turnaround concern.',
      ].join('\n'),
      epicRef: 'E3',
      wave: 'wave-002-core',
      status: 'IN_REVIEW',
      effort: 'M',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
      governanceSignal: 'REVIEW_BOTTLENECK',
      seedPR: {
        branchName: 'sandbox/session-management',
        prTitle: 'feat: implement Redis-backed session management',
      },
      contextComments: [
        'PR submitted for review 4 days ago. No reviewers have responded yet. This is blocking the auth epic from progressing.',
      ],
    },
    {
      ref: 'T13',
      title: 'Data export service',
      body: [
        '## Data Export Service',
        '',
        'Export processed data in multiple formats. Depends on data ingestion (T6, completed).',
        '',
        '### Acceptance Criteria',
        '- [ ] CSV and JSON export formats',
        '- [ ] Streaming export for large datasets',
        '- [ ] Export job tracking',
      ].join('\n'),
      epicRef: 'E2',
      wave: 'wave-002-core',
      status: 'READY_FOR_DEV',
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
      dependencyRefs: ['T6'],
    },
    {
      ref: 'T14',
      title: 'Batch processing',
      body: [
        '## Batch Processing',
        '',
        'Batch processing framework for scheduled data operations.',
        'Depends on data export service (T13) for data format contracts.',
        '',
        '### Acceptance Criteria',
        '- [ ] Scheduled batch jobs via cron',
        '- [ ] Retry logic for failed batches',
        '- [ ] Batch progress monitoring',
      ].join('\n'),
      epicRef: 'E2',
      wave: 'wave-002-core',
      status: 'IN_REFINEMENT',
      effort: 'XL',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
      dependencyRefs: ['T13'],
    },
    {
      ref: 'T15',
      title: 'Error recovery system',
      body: [
        '## Error Recovery System',
        '',
        'Automated error recovery and retry mechanisms.',
        '',
        '### Acceptance Criteria',
        '- [ ] Dead letter queue for failed operations',
        '- [ ] Configurable retry policies',
        '- [ ] Error classification and routing',
      ].join('\n'),
      epicRef: 'E2',
      wave: 'wave-002-core',
      status: 'DONE',
      effort: 'M',
      riskLevel: 'HIGH',
      aiSuitability: 'AI_REVIEWED',
    },

    // ─── Wave 3 — Advanced (PLANNED) ───
    {
      ref: 'T16',
      title: 'Role-based access control',
      body: [
        '## Role-Based Access Control',
        '',
        'RBAC system for fine-grained permissions. Depends on auth token service and session management.',
        '',
        '### Acceptance Criteria',
        '- [ ] Role definition and assignment',
        '- [ ] Permission checking middleware',
        '- [ ] Role hierarchy support',
        '',
        '### Governance Signal',
        'EPIC INTEGRITY VIOLATION — this task is in Auth epic (E3) but assigned to wave-003,',
        'while other Auth tasks (T10, T11, T12) are in wave-002.',
        '/compliance should detect this as a Principle 1 violation.',
      ].join('\n'),
      epicRef: 'E3',
      wave: 'wave-003-advanced',
      status: 'BACKLOG',
      effort: 'L',
      riskLevel: 'CRITICAL',
      aiSuitability: 'HUMAN_ONLY',
      dependencyRefs: ['T10', 'T12'],
      governanceSignal: 'EPIC_INTEGRITY_VIOLATION',
    },
    {
      ref: 'T17',
      title: 'Dashboard layout engine',
      body: [
        '## Dashboard Layout Engine',
        '',
        'Flexible grid-based layout engine for dashboards.',
        '',
        '### Acceptance Criteria',
        '- [ ] Grid layout with drag-and-drop',
        '- [ ] Responsive breakpoints',
        '- [ ] Layout persistence',
      ].join('\n'),
      epicRef: 'E4',
      wave: 'wave-003-advanced',
      status: 'BACKLOG',
      effort: 'XL',
      riskLevel: 'MEDIUM',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T18',
      title: 'Widget framework',
      body: [
        '## Widget Framework',
        '',
        'Pluggable widget framework for dashboard components. Depends on layout engine.',
        '',
        '### Acceptance Criteria',
        '- [ ] Widget registration API',
        '- [ ] Standard widget library (chart, table, metric)',
        '- [ ] Widget configuration persistence',
      ].join('\n'),
      epicRef: 'E4',
      wave: 'wave-003-advanced',
      status: 'BACKLOG',
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
      dependencyRefs: ['T17'],
    },

    // ─── Wave 4 — Polish (PLANNED) ───
    {
      ref: 'T19',
      title: 'User guide',
      body: [
        '## User Guide',
        '',
        'Comprehensive user guide for the platform.',
        '',
        '### Acceptance Criteria',
        '- [ ] Getting started guide',
        '- [ ] Feature walkthroughs with screenshots',
        '- [ ] Troubleshooting section',
      ].join('\n'),
      epicRef: 'E5',
      wave: 'wave-004-polish',
      status: 'BACKLOG',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },
    {
      ref: 'T20',
      title: 'API reference docs',
      body: [
        '## API Reference Documentation',
        '',
        'Auto-generated API reference from OpenAPI spec. Depends on user guide for structure.',
        '',
        '### Acceptance Criteria',
        '- [ ] Generated from OpenAPI spec',
        '- [ ] Interactive API explorer',
        '- [ ] Authentication examples',
      ].join('\n'),
      epicRef: 'E5',
      wave: 'wave-004-polish',
      status: 'BACKLOG',
      effort: 'L',
      riskLevel: 'LOW',
      aiSuitability: 'AI_REVIEWED',
      dependencyRefs: ['T19'],
    },
  ],
};
