/**
 * Scrum Sprint Showcase Scenario — a realistic mid-Sprint 14 project state
 * for an e-commerce checkout team using standard Scrum.
 *
 * Narrative: Team building e-commerce checkout, mid-Sprint 14. Sprint 13 had
 * carry-over. Product backlog has future work.
 *
 * Embedded violations / governance signals:
 * 1. DoR Violation: T5 "Cart abandonment email" lacks acceptance criteria
 * 2. False Status: T10 "In Review" but no PR exists
 * 3. Review Bottleneck: T8 stale in review — 0 of 2 required reviewers
 * 4. Blocked dependency: T11 blocked by T3 (payment integration)
 * 5. Scope Creep Risk: T15 (auth migration) sitting in backlog as XL/CRITICAL
 *
 * Work item types exercised: story, bug, spike, tech-debt, chore
 * Scrum states: BACKLOG, SPRINT, IN_PROGRESS, IN_REVIEW, DONE, BLOCKED
 */

import type { SandboxScenario } from '../types.js';

export const SCRUM_SPRINT: SandboxScenario = {
  id: 'scrum-sprint',
  name: 'Scrum Sprint Showcase',
  description: 'E-commerce checkout team mid-Sprint 14 with carry-over, mixed work item types, and governance signals',
  profileId: 'scrum',

  // ─── Container Instances (Sprints) ───
  containerInstances: [
    {
      ref: 'S13',
      containerType: 'sprint',
      name: 'Sprint 13',
      state: 'completed',
    },
    {
      ref: 'S14',
      containerType: 'sprint',
      name: 'Sprint 14',
      state: 'active',
    },
  ],

  // ─── Parent Issues ───
  // Standard Scrum has no epic-like parent in-sprint
  parentIssues: [],

  // ─── Tasks ───
  tasks: [
    // ─── Sprint 13 Carry-Over (2 tasks, DONE) ───
    {
      ref: 'T1',
      title: 'User registration flow',
      body: [
        '## User Registration Flow',
        '',
        'Implement the full user registration experience including email verification,',
        'password strength validation, and welcome onboarding sequence.',
        '',
        '### Acceptance Criteria',
        '- [ ] Registration form with email, password, and display name',
        '- [ ] Email verification link sent on sign-up',
        '- [ ] Password strength meter with minimum requirements',
        '- [ ] Welcome email triggered after verification',
        '- [ ] Duplicate email detection with clear error message',
      ].join('\n'),
      containers: { sprint: 'Sprint 13' },
      status: 'DONE',
      labels: ['type:story'],
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T2',
      title: 'Fix cart total rounding',
      body: [
        '## Fix Cart Total Rounding',
        '',
        'Cart total displays incorrect values when items have prices with more than',
        '2 decimal places. Rounding errors accumulate across line items.',
        '',
        '### Steps to Reproduce',
        '1. Add item at $19.999 to cart',
        '2. Add item at $4.995 to cart',
        '3. Cart total shows $25.00 instead of $24.99',
        '',
        '### Acceptance Criteria',
        '- [ ] All line items rounded to 2 decimal places before summing',
        '- [ ] Cart total matches sum of displayed line item prices',
        '- [ ] Existing order history unaffected by the fix',
      ].join('\n'),
      containers: { sprint: 'Sprint 13' },
      status: 'DONE',
      labels: ['type:bug'],
      effort: 'S',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },

    // ─── Sprint 14 Active (10 tasks, mixed states) ───
    {
      ref: 'T3',
      title: 'Checkout payment integration',
      body: [
        '## Checkout Payment Integration',
        '',
        'Integrate Stripe as the primary payment gateway for the checkout flow.',
        'Handles credit card, debit card, and Apple Pay.',
        '',
        '### Acceptance Criteria',
        '- [ ] Stripe Elements embedded in checkout page',
        '- [ ] Credit/debit card payments processed successfully',
        '- [ ] Apple Pay available on supported browsers',
        '- [ ] Payment intent created server-side with idempotency key',
        '- [ ] Failed payments show clear error messages to user',
        '- [ ] 3D Secure handled for cards that require it',
        '- [ ] Payment confirmation page shown on success',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'IN_PROGRESS',
      labels: ['type:story'],
      effort: 'XL',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T4',
      title: 'Shipping calculator',
      body: [
        '## Shipping Calculator',
        '',
        'Calculate shipping costs based on destination, weight, and selected carrier.',
        '',
        '### Acceptance Criteria',
        '- [ ] Support USPS, UPS, and FedEx rate lookups',
        '- [ ] Shipping estimate displayed before checkout',
        '- [ ] Free shipping threshold configurable per store',
        '- [ ] International shipping with customs estimate',
        '- [ ] Fallback flat rate when carrier API is unavailable',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'SPRINT',
      labels: ['type:story'],
      effort: 'M',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T5',
      title: 'Cart abandonment email',
      body: [
        '## Cart Abandonment Email',
        '',
        'Send a reminder email to users who add items to their cart but do not',
        'complete checkout within 24 hours. Should include the cart contents and',
        'a direct link back to their cart.',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'SPRINT',
      labels: ['type:story'],
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
      governanceSignal: 'DOR_VIOLATION',
    },
    {
      ref: 'T6',
      title: 'Fix currency display bug',
      body: [
        '## Fix Currency Display Bug',
        '',
        'Currency symbol not rendering correctly for non-USD locales.',
        'EUR shows as "EUR 19.99" instead of the proper euro sign.',
        '',
        '### Steps to Reproduce',
        '1. Set locale to de-DE',
        '2. View any product page',
        '3. Price displays "EUR 19.99" instead of expected format',
        '',
        '### Acceptance Criteria',
        '- [ ] Currency symbol renders correctly for USD, EUR, GBP, JPY',
        '- [ ] Locale-aware number formatting (comma vs period for decimals)',
        '- [ ] Existing prices in database unaffected',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'IN_PROGRESS',
      labels: ['type:bug'],
      effort: 'S',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },
    {
      ref: 'T7',
      title: 'Investigate payment gateway options',
      body: [
        '## Investigate Payment Gateway Options',
        '',
        'Spike to evaluate alternative/backup payment gateways in case of Stripe',
        'outages or regional restrictions. Compare Adyen, Braintree, and Square.',
        '',
        '### Spike Outputs',
        '- [ ] Comparison matrix: fees, supported regions, currencies, PCI scope',
        '- [ ] Integration complexity estimate for top 2 candidates',
        '- [ ] Recommendation document with trade-offs',
        '',
        '### Notes',
        'Spike — relaxed Definition of Done. No production code required.',
        'Deliverable is a written recommendation.',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'IN_REVIEW',
      labels: ['type:spike'],
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T8',
      title: 'Refactor order processing',
      body: [
        '## Refactor Order Processing',
        '',
        'Modernize the order processing pipeline from the monolithic handler to',
        'a composable step-based architecture. Reduces coupling and makes it',
        'easier to add new order types (subscriptions, pre-orders).',
        '',
        '### Acceptance Criteria',
        '- [ ] OrderPipeline class with composable steps',
        '- [ ] Existing order flow produces identical results (behavior-preserving)',
        '- [ ] New pipeline step interface documented',
        '- [ ] Performance regression tests pass (< 5% overhead)',
        '- [ ] Rollback strategy documented in case of production issues',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'IN_REVIEW',
      labels: ['type:tech-debt'],
      effort: 'L',
      riskLevel: 'HIGH',
      aiSuitability: 'AI_REVIEWED',
      governanceSignal: 'REVIEW_BOTTLENECK',
      seedPR: {
        branchName: 'sandbox/refactor-order-processing',
        prTitle: 'refactor: modernize order processing pipeline',
      },
      contextComments: [
        'PR submitted for review 3 days ago. Needs 2 reviewers for tech-debt but has 0 reviews.',
      ],
    },
    {
      ref: 'T9',
      title: 'Update CI config',
      body: [
        '## Update CI Config',
        '',
        'Update GitHub Actions workflows to use Node 20 and add caching for',
        'npm dependencies to speed up CI runs.',
        '',
        '### Acceptance Criteria',
        '- [ ] CI uses Node 20 LTS',
        '- [ ] npm cache restored between runs',
        '- [ ] Build time reduced by at least 30%',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'DONE',
      labels: ['type:chore'],
      effort: 'XS',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },
    {
      ref: 'T10',
      title: 'Add order confirmation page',
      body: [
        '## Add Order Confirmation Page',
        '',
        'Display a confirmation page after successful checkout with order summary,',
        'estimated delivery, and tracking information.',
        '',
        '### Acceptance Criteria',
        '- [ ] Order summary with line items, totals, and payment method',
        '- [ ] Estimated delivery date based on shipping method',
        '- [ ] Order confirmation email triggered',
        '- [ ] Print-friendly version available',
        '- [ ] Social sharing option for purchases',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'IN_REVIEW',
      labels: ['type:story'],
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
      governanceSignal: 'FALSE_STATUS',
      contextComments: [
        'Moved to In Review 4 days ago but no PR has been created yet.',
      ],
    },
    {
      ref: 'T11',
      title: 'Fix session timeout',
      body: [
        '## Fix Session Timeout',
        '',
        'User sessions expire during checkout causing payment failures.',
        'Session timeout needs to be extended or refreshed during active',
        'checkout flow.',
        '',
        '### Steps to Reproduce',
        '1. Start checkout flow',
        '2. Wait 15 minutes on payment page',
        '3. Submit payment — 401 Unauthorized error',
        '',
        '### Acceptance Criteria',
        '- [ ] Session refreshed on each checkout step',
        '- [ ] Graceful redirect to login if session truly expired',
        '- [ ] Cart contents preserved across re-authentication',
        '- [ ] Payment intent not lost on session refresh',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'BLOCKED',
      labels: ['type:bug'],
      effort: 'M',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
      dependencyRefs: ['T3'],
      contextComments: [
        'Blocked by #T3 — payment integration changes may affect session handling.',
      ],
    },
    {
      ref: 'T12',
      title: 'Update API documentation',
      body: [
        '## Update API Documentation',
        '',
        'Update the public API docs to reflect new checkout and payment endpoints',
        'added in Sprint 14.',
        '',
        '### Acceptance Criteria',
        '- [ ] New endpoints documented with request/response examples',
        '- [ ] Error codes and descriptions updated',
        '- [ ] Authentication requirements listed per endpoint',
      ].join('\n'),
      containers: { sprint: 'Sprint 14' },
      status: 'SPRINT',
      labels: ['type:chore'],
      effort: 'S',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },

    // ─── Product Backlog (3 tasks, BACKLOG) ───
    {
      ref: 'T13',
      title: 'Wishlist feature',
      body: [
        '## Wishlist Feature',
        '',
        'Allow users to save products to a wishlist for later purchase.',
        'Wishlist items should persist across sessions and be shareable.',
        '',
        '### Acceptance Criteria',
        '- [ ] Add/remove items from wishlist',
        '- [ ] Wishlist persists across sessions (logged-in users)',
        '- [ ] Shareable wishlist link',
        '- [ ] "Move to cart" action from wishlist',
        '- [ ] Wishlist item count in header navigation',
      ].join('\n'),
      containers: {},
      status: 'BACKLOG',
      labels: ['type:story'],
      effort: 'XL',
      riskLevel: 'MEDIUM',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T14',
      title: 'Performance audit',
      body: [
        '## Performance Audit',
        '',
        'Spike to audit the checkout flow performance. Identify bottlenecks,',
        'measure Core Web Vitals, and produce an optimization roadmap.',
        '',
        '### Spike Outputs',
        '- [ ] Lighthouse report for checkout pages',
        '- [ ] Database query analysis for order processing',
        '- [ ] API response time measurements under load',
        '- [ ] Prioritized optimization backlog',
      ].join('\n'),
      containers: {},
      status: 'BACKLOG',
      labels: ['type:spike'],
      effort: 'L',
      riskLevel: 'LOW',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T15',
      title: 'Migrate to new auth provider',
      body: [
        '## Migrate to New Auth Provider',
        '',
        'Replace the legacy in-house auth system with Auth0 for improved security,',
        'SSO support, and reduced maintenance burden. High-risk migration affecting',
        'all authenticated endpoints.',
        '',
        '### Acceptance Criteria',
        '- [ ] Auth0 tenant configured for all environments',
        '- [ ] Token format migration plan with zero-downtime rollover',
        '- [ ] All existing user sessions migrated without forced logout',
        '- [ ] SSO integration for enterprise customers',
        '- [ ] Rollback runbook with < 5 minute recovery',
        '- [ ] Security review sign-off before production deploy',
      ].join('\n'),
      containers: {},
      status: 'BACKLOG',
      labels: ['type:tech-debt'],
      effort: 'XL',
      riskLevel: 'CRITICAL',
      aiSuitability: 'HUMAN_ONLY',
      governanceSignal: 'SCOPE_CREEP_RISK',
    },
  ],

  // ─── Audit Events ───
  auditEvents: [
    // Sprint 13 tasks T1, T2 (completed 7-5 days ago)
    { taskRef: 'T1', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 8, hoursOffset: 0 },
    { taskRef: 'T1', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 7, hoursOffset: 0 },
    { taskRef: 'T1', transition: 'review', fromStatus: 'IN_PROGRESS', toStatus: 'IN_REVIEW', daysAgo: 6, hoursOffset: 0 },
    { taskRef: 'T1', transition: 'approve', fromStatus: 'IN_REVIEW', toStatus: 'DONE', daysAgo: 5, hoursOffset: 0 },
    { taskRef: 'T2', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 8, hoursOffset: 1 },
    { taskRef: 'T2', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 7, hoursOffset: 2 },
    { taskRef: 'T2', transition: 'approve', fromStatus: 'IN_PROGRESS', toStatus: 'DONE', daysAgo: 6, hoursOffset: 0 },

    // Sprint 14 tasks (3-0 days ago)
    { taskRef: 'T3', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 4, hoursOffset: 0 },
    { taskRef: 'T3', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 3, hoursOffset: 0 },
    { taskRef: 'T6', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 4, hoursOffset: 1 },
    { taskRef: 'T6', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 2, hoursOffset: 0 },
    { taskRef: 'T7', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 4, hoursOffset: 2 },
    { taskRef: 'T7', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 3, hoursOffset: 2 },
    { taskRef: 'T7', transition: 'review', fromStatus: 'IN_PROGRESS', toStatus: 'IN_REVIEW', daysAgo: 1, hoursOffset: 0 },
    { taskRef: 'T8', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 4, hoursOffset: 3 },
    { taskRef: 'T8', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 3, hoursOffset: 4 },
    { taskRef: 'T8', transition: 'review', fromStatus: 'IN_PROGRESS', toStatus: 'IN_REVIEW', daysAgo: 0, hoursOffset: -8 },
    { taskRef: 'T9', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 4, hoursOffset: 4 },
    { taskRef: 'T9', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 3, hoursOffset: 6 },
    { taskRef: 'T9', transition: 'approve', fromStatus: 'IN_PROGRESS', toStatus: 'DONE', daysAgo: 2, hoursOffset: 0 },
    { taskRef: 'T10', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 4, hoursOffset: 5 },
    { taskRef: 'T10', transition: 'start', fromStatus: 'SPRINT', toStatus: 'IN_PROGRESS', daysAgo: 3, hoursOffset: 1 },
    { taskRef: 'T10', transition: 'review', fromStatus: 'IN_PROGRESS', toStatus: 'IN_REVIEW', daysAgo: 0, hoursOffset: -4 },
    { taskRef: 'T11', transition: 'plan', fromStatus: 'BACKLOG', toStatus: 'SPRINT', daysAgo: 4, hoursOffset: 6 },
    { taskRef: 'T11', transition: 'block', fromStatus: 'SPRINT', toStatus: 'BLOCKED', daysAgo: 3, hoursOffset: 3 },
  ],

  // ─── Agents ───
  agents: {
    agents: [
      { agentId: 'agent-alpha', name: 'Alpha', role: 'coding', capabilities: ['backend', 'payments'] },
      { agentId: 'agent-beta', name: 'Beta', role: 'coding', capabilities: ['frontend', 'ui'] },
    ],
    locks: [
      { agentId: 'agent-alpha', taskRef: 'T3' },
    ],
  },

  // ─── Memory Seed ───
  memorySeed: [
    '# Sandbox Scrum Sprint Memory Seed',
    '',
    '## Sprint 13 Retro',
    '- **Carry-over**: T1 (User registration) was originally estimated as M but turned out to be L',
    '  — completed late in Sprint 13, signaling estimation accuracy issues on stories',
    '- **Bug velocity**: T2 (Cart total rounding) was a quick fix, resolved same day it was started',
    '- **Carry-over rate**: 1 of 2 stories carried over late — 50% story carry-over is a red flag',
    '',
    '## Sprint 14 Burndown Trajectory',
    '- **Committed**: 10 tasks across 5 work item types (4 stories, 2 bugs, 1 spike, 2 tech-debt, 1 chore)',
    '- **Done**: 1/10 (T9 — CI config chore, XS effort). Only 10% completion mid-sprint.',
    '- **In Progress**: 2 tasks (T3 payment integration XL, T6 currency bug S)',
    '- **In Review**: 3 tasks (T7 spike, T8 tech-debt, T10 story) — review queue is building up',
    '- **Blocked**: 1 task (T11 session timeout, blocked by T3)',
    '- **Not Started**: 3 tasks still in SPRINT state (T4, T5, T12)',
    '- **Burndown assessment**: Behind pace. XL payment integration (T3) is the critical path.',
    '',
    '## Governance Signals',
    '- **DoR Violation (T5)**: Cart abandonment email has no acceptance criteria — should not be started',
    '- **False Status (T10)**: Order confirmation page is In Review with no PR — status is misleading',
    '- **Review Bottleneck (T8)**: Order processing refactor PR has 0 of 2 required reviews after 3 days',
    '- **Blocked Chain**: T11 (session timeout) blocked by T3 (payment integration) — high-risk dependency',
    '- **Scope Creep Risk (T15)**: Auth migration in backlog is XL/CRITICAL — if pulled into sprint, it will blow capacity',
    '',
    '## Sprint Goal Alignment',
    '- Sprint 14 goal: "Complete checkout flow with payment integration"',
    '- T3 (payment), T4 (shipping), T10 (confirmation) are goal-critical stories',
    '- T5 (abandonment email) is nice-to-have, not goal-critical — deprioritize if sprint is at risk',
    '- T7 (spike) and T8 (tech-debt) are improvement work, not goal-aligned — monitor for time boxing',
  ].join('\n'),
};
