/**
 * Shape Up Cycle Showcase Scenario — week 5 of a 6-week cycle.
 *
 * Narrative: Product team deep into cycle-003. Two active bets with
 * diverging trajectories, one bet correctly killed at week 4, and
 * raw ideas being shaped for the next betting table.
 *
 * Embedded governance signals:
 * 1. Circuit Breaker Countdown: 1 week left — search bet at risk
 * 2. Scope Creep: T9 (search analytics) was NOT in the original pitch
 * 3. False Status: T8 marked QA but no PR exists
 * 4. Integrity Violation: T13 assigned to wrong cycle (cycle-002 vs cycle-003)
 * 5. Killed Bet: B3 onboarding flow — correct circuit breaker behavior
 */

import type { SandboxScenario } from '../types.js';

export const SHAPE_UP_CYCLE: SandboxScenario = {
  id: 'shape-up-cycle',
  name: 'Shape Up Cycle Showcase',
  description: 'Week 5 of a 6-week cycle — one bet on track, one approaching circuit breaker, one correctly killed',
  profileId: 'shape-up',

  // ─── Container Instances ───
  containerInstances: [
    {
      ref: 'C2',
      containerType: 'cycle',
      name: 'cycle-002-mobile',
      state: 'completed',
    },
    {
      ref: 'C3',
      containerType: 'cycle',
      name: 'cycle-003-notifications',
      state: 'active',
      metadata: {
        startDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      },
    },
    {
      ref: 'B1',
      containerType: 'bet',
      name: 'bet-push-notifications',
      state: 'active',
    },
    {
      ref: 'B2',
      containerType: 'bet',
      name: 'bet-search-redesign',
      state: 'active',
    },
    {
      ref: 'B3',
      containerType: 'bet',
      name: 'bet-onboarding-flow',
      state: 'killed',
    },
    {
      ref: 'SC1',
      containerType: 'scope',
      name: 'scope-ios-push',
      state: 'active',
    },
    {
      ref: 'SC2',
      containerType: 'scope',
      name: 'scope-android-push',
      state: 'active',
    },
    {
      ref: 'SC3',
      containerType: 'scope',
      name: 'scope-push-settings',
      state: 'active',
    },
    {
      ref: 'SC4',
      containerType: 'scope',
      name: 'scope-search-ui',
      state: 'active',
    },
    {
      ref: 'SC5',
      containerType: 'scope',
      name: 'scope-search-index',
      state: 'active',
    },
    {
      ref: 'SC6',
      containerType: 'scope',
      name: 'scope-search-filters',
      state: 'active',
    },
    {
      ref: 'SC7',
      containerType: 'scope',
      name: 'scope-search-ranking',
      state: 'planned',
    },
    {
      ref: 'SC8',
      containerType: 'scope',
      name: 'scope-search-caching',
      state: 'active',
    },
    {
      ref: 'SC9',
      containerType: 'scope',
      name: 'scope-search-analytics',
      state: 'planned',
    },
    {
      ref: 'SC10',
      containerType: 'scope',
      name: 'scope-welcome-screen',
      state: 'killed',
    },
    {
      ref: 'SC11',
      containerType: 'scope',
      name: 'scope-tutorial-flow',
      state: 'killed',
    },
  ],

  // ─── Parent Issues (Bets) ───
  parentIssues: [
    {
      ref: 'B1',
      title: '[Bet] Push Notifications',
      body: [
        '## Push Notifications',
        '',
        'Implement push notification infrastructure across iOS and Android platforms.',
        'Users should be able to receive timely, relevant notifications and manage',
        'their notification preferences through a dedicated settings UI.',
        '',
        '### Appetite',
        '6-week cycle. 3 scopes: iOS push, Android push, push settings.',
        '',
        '### Hill Chart',
        'Over the hill — iOS shipped, Android in QA, settings still building.',
      ].join('\n'),
    },
    {
      ref: 'B2',
      title: '[Bet] Search Redesign',
      body: [
        '## Search Redesign',
        '',
        'Rebuild the search experience with new UI, improved indexing, filters,',
        'ranking algorithm, and result caching.',
        '',
        '### Appetite',
        '6-week cycle. Originally shaped with 3 scopes (UI, index, filters).',
        '',
        '### Risk',
        '**6 scopes vs 3 originally shaped — scope creep risk.** Ranking,',
        'caching, and analytics were added during the building phase. The bet',
        'now has double the surface area of the original pitch. Circuit breaker',
        'countdown: 1 week remaining.',
      ].join('\n'),
    },
    {
      ref: 'B3',
      title: '[Bet] Onboarding Flow',
      body: [
        '## Onboarding Flow',
        '',
        'Redesign the new-user onboarding experience with a welcome screen',
        'and interactive tutorial flow.',
        '',
        '### Status: KILLED',
        'This bet was intentionally killed at week 4. The welcome screen and',
        'tutorial flow were not converging — team chose to exercise the circuit',
        'breaker rather than let the bet drag the cycle. Correct Shape Up behavior.',
        '',
        '### Post-Mortem',
        'The pitch underestimated the design exploration needed. May return as',
        'a reshaped pitch in a future betting table with tighter scope.',
      ].join('\n'),
    },
  ],

  // ─── Tasks ───
  tasks: [
    // ─── Bet: Push Notifications (on track) ───
    {
      ref: 'T1',
      title: 'iOS push notification service',
      body: [
        '## iOS Push Notification Service',
        '',
        'Implement the APNs integration for iOS push notifications.',
        '',
        '### Acceptance Criteria',
        '- [ ] APNs provider configured with certificate-based auth',
        '- [ ] Silent and alert push types supported',
        '- [ ] Delivery receipts tracked and logged',
        '- [ ] Rate limiting respects APNs quotas',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B1', scope: 'scope-ios-push' },
      parentRef: 'B1',
      status: 'SHIPPED',
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T2',
      title: 'Android push notification service',
      body: [
        '## Android Push Notification Service',
        '',
        'Implement FCM integration for Android push notifications.',
        '',
        '### Acceptance Criteria',
        '- [ ] FCM v1 API integration with service account auth',
        '- [ ] Topic-based and device-targeted delivery',
        '- [ ] Notification payload builder with data messages',
        '- [ ] Error handling for invalid tokens and quota exhaustion',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B1', scope: 'scope-android-push' },
      parentRef: 'B1',
      status: 'QA',
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
      seedPR: {
        branchName: 'sandbox/android-push',
        prTitle: 'feat: implement Android push notification service',
      },
    },
    {
      ref: 'T3',
      title: 'Push notification settings UI',
      body: [
        '## Push Notification Settings UI',
        '',
        'User-facing settings screen for managing notification preferences.',
        '',
        '### Acceptance Criteria',
        '- [ ] Toggle for each notification category (marketing, transactional, system)',
        '- [ ] Quiet hours configuration',
        '- [ ] Per-device registration display',
        '- [ ] Changes persisted and synced across devices',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B1', scope: 'scope-push-settings' },
      parentRef: 'B1',
      status: 'BUILDING',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'HYBRID',
    },

    // ─── Bet: Search Redesign (at risk — circuit breaker approaching) ───
    {
      ref: 'T4',
      title: 'Search UI component',
      body: [
        '## Search UI Component',
        '',
        'New search input with instant results preview and keyboard navigation.',
        '',
        '### Acceptance Criteria',
        '- [ ] Typeahead with debounced API calls',
        '- [ ] Keyboard navigation (up/down/enter/escape)',
        '- [ ] Results preview panel with highlighted matches',
        '- [ ] Mobile-responsive layout',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B2', scope: 'scope-search-ui' },
      parentRef: 'B2',
      status: 'SHIPPED',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T5',
      title: 'Search index rebuild',
      body: [
        '## Search Index Rebuild',
        '',
        'Rebuild the search index with new schema and data migration.',
        'This is the critical-path task for the search bet.',
        '',
        '### Acceptance Criteria',
        '- [ ] New index schema supports faceted search',
        '- [ ] Zero-downtime reindex strategy',
        '- [ ] Data migration from legacy index complete',
        '- [ ] Index rebuild < 30 minutes for full corpus',
        '',
        '### Risk',
        'XL effort, HIGH risk. Complex data migration. 3 weeks into this scope.',
        'Blocking search autocomplete (T10).',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B2', scope: 'scope-search-index' },
      parentRef: 'B2',
      status: 'BUILDING',
      effort: 'XL',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
      contextComments: [
        'Search index rebuild proving slower than expected. Complex data migration required. 3 weeks into this scope.',
      ],
    },
    {
      ref: 'T6',
      title: 'Search filter controls',
      body: [
        '## Search Filter Controls',
        '',
        'Faceted filter UI for narrowing search results.',
        '',
        '### Acceptance Criteria',
        '- [ ] Filter by category, date range, and content type',
        '- [ ] Filter counts update dynamically',
        '- [ ] URL-serializable filter state for shareable searches',
        '- [ ] Clear all / clear individual filter actions',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B2', scope: 'scope-search-filters' },
      parentRef: 'B2',
      status: 'BUILDING',
      effort: 'M',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T7',
      title: 'Search ranking algorithm',
      body: [
        '## Search Ranking Algorithm',
        '',
        'Implement relevance scoring and result ranking. Shaped and bet on,',
        'but building has not started.',
        '',
        '### Acceptance Criteria',
        '- [ ] TF-IDF based relevance scoring',
        '- [ ] Recency boost for recent content',
        '- [ ] Personalization signal from user history',
        '- [ ] A/B test harness for ranking experiments',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B2', scope: 'scope-search-ranking' },
      parentRef: 'B2',
      status: 'BET',
      effort: 'L',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T8',
      title: 'Search result caching',
      body: [
        '## Search Result Caching',
        '',
        'Cache layer for search results to reduce index load.',
        '',
        '### Acceptance Criteria',
        '- [ ] LRU cache with configurable TTL',
        '- [ ] Cache invalidation on index update',
        '- [ ] Cache hit/miss metrics exposed',
        '- [ ] Bypass cache for authenticated searches',
        '',
        '### Governance Signal',
        'FALSE STATUS — moved to QA 2 days ago but no PR has been created.',
        'Implementation is still in progress.',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B2', scope: 'scope-search-caching' },
      parentRef: 'B2',
      status: 'QA',
      effort: 'M',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_ONLY',
      governanceSignal: 'FALSE_STATUS',
      contextComments: [
        'Moved to QA 2 days ago but no PR has been created yet. Implementation still in progress.',
      ],
    },
    {
      ref: 'T9',
      title: 'Search analytics dashboard',
      body: [
        '## Search Analytics Dashboard',
        '',
        'Dashboard showing search usage patterns, popular queries, and zero-result rates.',
        '',
        '### Acceptance Criteria',
        '- [ ] Top queries report with click-through rates',
        '- [ ] Zero-result query identification',
        '- [ ] Search latency percentiles (p50, p95, p99)',
        '- [ ] Daily/weekly trend charts',
        '',
        '### Governance Signal',
        'SCOPE CREEP — this scope was NOT in the original pitch. Added during',
        'the building phase. Bet now has 6 scopes vs 3 originally shaped.',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B2', scope: 'scope-search-analytics' },
      parentRef: 'B2',
      status: 'BET',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_REVIEWED',
      governanceSignal: 'SCOPE_CREEP',
      contextComments: [
        'This scope was NOT in the original pitch. Added during building phase — 6 scopes when bet was shaped with 3.',
      ],
    },
    {
      ref: 'T10',
      title: 'Search autocomplete',
      body: [
        '## Search Autocomplete',
        '',
        'Autocomplete suggestions powered by the search index. Blocked by index rebuild.',
        '',
        '### Acceptance Criteria',
        '- [ ] Prefix-based suggestion generation',
        '- [ ] Popular query boosting',
        '- [ ] < 50ms response time for suggestions',
        '- [ ] Graceful degradation when index unavailable',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B2', scope: 'scope-search-index' },
      parentRef: 'B2',
      status: 'BLOCKED',
      effort: 'M',
      riskLevel: 'MEDIUM',
      aiSuitability: 'AI_REVIEWED',
      dependencyRefs: ['T5'],
      contextComments: [
        'Blocked by #T5 — waiting for search index rebuild completion.',
      ],
    },

    // ─── Bet: Onboarding Flow (killed — correct circuit breaker behavior) ───
    {
      ref: 'T11',
      title: 'Welcome screen redesign',
      body: [
        '## Welcome Screen Redesign',
        '',
        'New first-run experience with personalized onboarding flow.',
        '',
        '### Acceptance Criteria',
        '- [ ] Role-based welcome messaging',
        '- [ ] Animated walkthrough of key features',
        '- [ ] Skip option for returning users',
        '- [ ] Analytics tracking of completion rate',
        '',
        '### Status: KILLED',
        'Killed at week 4 as part of circuit breaker decision on bet-onboarding-flow.',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B3', scope: 'scope-welcome-screen' },
      parentRef: 'B3',
      status: 'KILLED',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_REVIEWED',
    },
    {
      ref: 'T12',
      title: 'Interactive tutorial flow',
      body: [
        '## Interactive Tutorial Flow',
        '',
        'Step-by-step interactive tutorial guiding new users through core workflows.',
        '',
        '### Acceptance Criteria',
        '- [ ] Tooltip-based guided tour',
        '- [ ] Progress indicator with step count',
        '- [ ] Contextual help triggers on first use of each feature',
        '- [ ] Tutorial state persisted per user',
        '',
        '### Status: KILLED',
        'Killed at week 4 as part of circuit breaker decision on bet-onboarding-flow.',
      ].join('\n'),
      containers: { cycle: 'cycle-003-notifications', bet: '#B3', scope: 'scope-tutorial-flow' },
      parentRef: 'B3',
      status: 'KILLED',
      effort: 'L',
      riskLevel: 'MEDIUM',
      aiSuitability: 'HYBRID',
    },

    // ─── Integrity Violation: wrong cycle ───
    {
      ref: 'T13',
      title: 'Email notification templates',
      body: [
        '## Email Notification Templates',
        '',
        'Reusable email templates for notification delivery fallback.',
        '',
        '### Acceptance Criteria',
        '- [ ] HTML and plain-text template variants',
        '- [ ] Template variable interpolation',
        '- [ ] Unsubscribe link injection',
        '- [ ] Preview and test-send capability',
        '',
        '### Governance Signal',
        'INTEGRITY VIOLATION — this task is in bet-push-notifications but',
        'assigned to cycle-002-mobile instead of cycle-003-notifications.',
        'All tasks in a bet must be in the same cycle.',
      ].join('\n'),
      containers: { cycle: 'cycle-002-mobile', bet: '#B1', scope: 'scope-ios-push' },
      parentRef: 'B1',
      status: 'BUILDING',
      effort: 'S',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
      governanceSignal: 'INTEGRITY_VIOLATION',
    },

    // ─── Cooldown / Raw Ideas (no containers) ───
    {
      ref: 'T14',
      title: 'Real-time collaboration',
      body: [
        '## Real-Time Collaboration',
        '',
        'Raw idea for adding real-time collaborative editing capabilities.',
        '',
        '### Unshaped Notes',
        '- WebSocket or SSE for real-time sync',
        '- Operational transform or CRDT for conflict resolution',
        '- Presence indicators showing active users',
        '- Cursor and selection broadcasting',
        '',
        '### Open Questions',
        '- What is the appetite? Could be 6-week or 8-week depending on scope.',
        '- Do we need offline support? That pushes this to XL.',
        '- Which surfaces need collaboration first?',
      ].join('\n'),
      containers: {},
      status: 'RAW',
      effort: 'XL',
      riskLevel: 'HIGH',
      aiSuitability: 'HYBRID',
    },
    {
      ref: 'T15',
      title: 'Dark mode support',
      body: [
        '## Dark Mode Support',
        '',
        'Shaped pitch for system-wide dark mode.',
        '',
        '### Pitch',
        'Add a dark color scheme that respects system preferences and allows',
        'manual override. Design tokens already support theming — this is',
        'primarily a CSS variable audit and component-level testing pass.',
        '',
        '### Acceptance Criteria',
        '- [ ] System preference detection (prefers-color-scheme)',
        '- [ ] Manual toggle in user settings',
        '- [ ] All components render correctly in both modes',
        '- [ ] No flash of unstyled content on theme switch',
      ].join('\n'),
      containers: {},
      status: 'SHAPED',
      effort: 'M',
      riskLevel: 'LOW',
      aiSuitability: 'AI_ONLY',
    },
    {
      ref: 'T16',
      title: 'Offline mode',
      body: [
        '## Offline Mode',
        '',
        'Shaped pitch for offline-first data access.',
        '',
        '### Pitch',
        'Service worker caching strategy with IndexedDB for local data.',
        'Users can view and create items offline; sync resolves on reconnect.',
        'Conflict resolution follows last-write-wins with manual merge for',
        'concurrent edits.',
        '',
        '### Acceptance Criteria',
        '- [ ] Service worker with cache-first strategy for assets',
        '- [ ] IndexedDB store mirrors critical server state',
        '- [ ] Offline queue for write operations',
        '- [ ] Sync indicator showing pending/synced state',
        '',
        '### Risk',
        'CRITICAL risk — conflict resolution and data integrity are hard problems.',
        'Needs thorough shaping before betting.',
      ].join('\n'),
      containers: {},
      status: 'SHAPED',
      effort: 'XL',
      riskLevel: 'CRITICAL',
      aiSuitability: 'HYBRID',
    },
  ],

  // ─── Audit Events ───
  auditEvents: [
    // T1: iOS push — RAW → SHAPED → BET → BUILDING → QA → SHIPPED
    { taskRef: 'T1', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 40, hoursOffset: 0 },
    { taskRef: 'T1', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 0 },
    { taskRef: 'T1', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 33, hoursOffset: 0 },
    { taskRef: 'T1', transition: 'review', fromStatus: 'BUILDING', toStatus: 'QA', daysAgo: 14, hoursOffset: 0 },
    { taskRef: 'T1', transition: 'ship', fromStatus: 'QA', toStatus: 'SHIPPED', daysAgo: 10, hoursOffset: 0 },

    // T2: Android push — RAW → SHAPED → BET → BUILDING → QA
    { taskRef: 'T2', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 40, hoursOffset: 1 },
    { taskRef: 'T2', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 1 },
    { taskRef: 'T2', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 30, hoursOffset: 0 },
    { taskRef: 'T2', transition: 'review', fromStatus: 'BUILDING', toStatus: 'QA', daysAgo: 3, hoursOffset: 0 },

    // T3: Push settings — RAW → SHAPED → BET → BUILDING
    { taskRef: 'T3', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 40, hoursOffset: 2 },
    { taskRef: 'T3', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 2 },
    { taskRef: 'T3', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 20, hoursOffset: 0 },

    // T4: Search UI — RAW → SHAPED → BET → BUILDING → QA → SHIPPED
    { taskRef: 'T4', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 38, hoursOffset: 0 },
    { taskRef: 'T4', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 3 },
    { taskRef: 'T4', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 32, hoursOffset: 0 },
    { taskRef: 'T4', transition: 'review', fromStatus: 'BUILDING', toStatus: 'QA', daysAgo: 18, hoursOffset: 0 },
    { taskRef: 'T4', transition: 'ship', fromStatus: 'QA', toStatus: 'SHIPPED', daysAgo: 15, hoursOffset: 0 },

    // T5: Search index rebuild — RAW → SHAPED → BET → BUILDING
    { taskRef: 'T5', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 38, hoursOffset: 1 },
    { taskRef: 'T5', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 4 },
    { taskRef: 'T5', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 28, hoursOffset: 0 },

    // T6: Search filters — RAW → SHAPED → BET → BUILDING
    { taskRef: 'T6', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 38, hoursOffset: 2 },
    { taskRef: 'T6', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 5 },
    { taskRef: 'T6', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 21, hoursOffset: 0 },

    // T7: Search ranking — RAW → SHAPED → BET (not started)
    { taskRef: 'T7', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 38, hoursOffset: 3 },
    { taskRef: 'T7', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 6 },

    // T8: Search caching — RAW → SHAPED → BET → BUILDING → QA (false status)
    { taskRef: 'T8', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 38, hoursOffset: 4 },
    { taskRef: 'T8', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 7 },
    { taskRef: 'T8', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 14, hoursOffset: 0 },
    { taskRef: 'T8', transition: 'review', fromStatus: 'BUILDING', toStatus: 'QA', daysAgo: 2, hoursOffset: 0 },

    // T9: Search analytics — RAW → SHAPED → BET (scope creep — shaped mid-cycle)
    { taskRef: 'T9', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 20, hoursOffset: 0 },
    { taskRef: 'T9', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 15, hoursOffset: 0 },

    // T10: Search autocomplete — RAW → SHAPED → BET → BUILDING → BLOCKED
    { taskRef: 'T10', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 38, hoursOffset: 5 },
    { taskRef: 'T10', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 8 },
    { taskRef: 'T10', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 10, hoursOffset: 0 },
    { taskRef: 'T10', transition: 'block', fromStatus: 'BUILDING', toStatus: 'BLOCKED', daysAgo: 5, hoursOffset: 0 },

    // T11: Welcome screen — RAW → SHAPED → BET → BUILDING → KILLED
    { taskRef: 'T11', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 40, hoursOffset: 3 },
    { taskRef: 'T11', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 9 },
    { taskRef: 'T11', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 28, hoursOffset: 0 },
    { taskRef: 'T11', transition: 'kill', fromStatus: 'BUILDING', toStatus: 'KILLED', daysAgo: 7, hoursOffset: 0 },

    // T12: Tutorial flow — RAW → SHAPED → BET → BUILDING → KILLED
    { taskRef: 'T12', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 40, hoursOffset: 4 },
    { taskRef: 'T12', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 35, hoursOffset: 10 },
    { taskRef: 'T12', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 25, hoursOffset: 0 },
    { taskRef: 'T12', transition: 'kill', fromStatus: 'BUILDING', toStatus: 'KILLED', daysAgo: 7, hoursOffset: 1 },

    // T13: Email templates — RAW → SHAPED → BET → BUILDING (wrong cycle)
    { taskRef: 'T13', transition: 'shape', fromStatus: 'RAW', toStatus: 'SHAPED', daysAgo: 42, hoursOffset: 0 },
    { taskRef: 'T13', transition: 'bet', fromStatus: 'SHAPED', toStatus: 'BET', daysAgo: 40, hoursOffset: 0 },
    { taskRef: 'T13', transition: 'start', fromStatus: 'BET', toStatus: 'BUILDING', daysAgo: 38, hoursOffset: 0 },
  ],

  // ─── Agents ───
  agents: {
    agents: [
      { agentId: 'agent-alpha', name: 'Alpha', role: 'coding', capabilities: ['backend', 'search'] },
      { agentId: 'agent-beta', name: 'Beta', role: 'coding', capabilities: ['mobile', 'ui'] },
    ],
    locks: [
      { agentId: 'agent-alpha', taskRef: 'T5' },
    ],
  },

  // ─── Memory Seed ───
  memorySeed: [
    '# Sandbox Shape Up Cycle Memory Seed',
    '',
    '## Cycle Health — cycle-003-notifications',
    '- **Week**: 5 of 6 — circuit breaker deadline in 1 week',
    '- **Appetite consumed**: ~83% (35 of 42 days elapsed)',
    '- **Active bets**: 2 (push notifications, search redesign)',
    '- **Killed bets**: 1 (onboarding flow — correct circuit breaker at week 4)',
    '',
    '## Hill Chart Analysis',
    '- **bet-push-notifications**: Over the hill. iOS shipped, Android in QA, settings building.',
    '  On track to ship by cycle end.',
    '- **bet-search-redesign**: Stuck on the uphill. Index rebuild (T5) has been building for 3 weeks.',
    '  Only 2 of 7 tasks shipped/QA. 2 tasks not yet started. Circuit breaker territory.',
    '',
    '## Bet Health Summary',
    '- **Push Notifications** (B1): GREEN — 1 shipped, 1 in QA with PR, 1 building. Will ship.',
    '- **Search Redesign** (B2): RED — scope doubled from pitch (3→6 scopes), critical path blocked,',
    '  2 tasks still in BET state with 1 week left. Strong candidate for partial kill.',
    '- **Onboarding Flow** (B3): KILLED — correct behavior. Team recognized non-convergence at week 4.',
    '',
    '## Active Governance Signals',
    '- **Scope Creep**: T9 (search analytics) added mid-cycle — was NOT in original pitch',
    '- **False Status**: T8 (search caching) in QA but no PR exists — real status is still building',
    '- **Integrity Violation**: T13 (email templates) in bet-push-notifications but assigned to cycle-002-mobile',
    '- **Blocked**: T10 (search autocomplete) waiting on T5 (index rebuild) for 5 days',
    '',
    '## Circuit Breaker Countdown',
    '- 7 days remaining in cycle-003',
    '- Push notifications bet: likely ships (2/3 scopes done, 1 in progress)',
    '- Search redesign bet: 5 of 7 tasks NOT shipped — needs immediate scope cut decision',
    '- Recommendation: kill ranking (T7) and analytics (T9) scopes, focus on shipping index + filters',
    '',
    '## Killed Bet Analysis — Onboarding Flow',
    '- Killed at week 4 — 2 tasks transitioned BUILDING→KILLED',
    '- This is CORRECT Shape Up behavior: no extensions, appetite is fixed',
    '- Post-mortem: pitch underestimated design exploration, may reshape for future cycle',
    '',
    '## Active Agents',
    '- **agent-alpha**: coding (backend, search) — locked on T5 (search index rebuild)',
    '- **agent-beta**: coding (mobile, ui) — available for assignment',
    '',
    '## Cooldown Pipeline',
    '- T14 (Real-time collaboration): RAW — needs shaping, XL appetite',
    '- T15 (Dark mode): SHAPED — ready for betting table, M appetite',
    '- T16 (Offline mode): SHAPED — CRITICAL risk, XL appetite, needs more shaping',
  ].join('\n'),
};
